/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrpgindexImport } from './routes/trpgindex'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TrpgindexRoute = TrpgindexImport.update({
  id: '/trpgindex',
  path: '/trpgindex',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/trpgindex': {
      id: '/trpgindex'
      path: '/trpgindex'
      fullPath: '/trpgindex'
      preLoaderRoute: typeof TrpgindexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trpgindex': typeof TrpgindexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trpgindex': typeof TrpgindexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/trpgindex': typeof TrpgindexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trpgindex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trpgindex'
  id: '__root__' | '/' | '/trpgindex'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrpgindexRoute: typeof TrpgindexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrpgindexRoute: TrpgindexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/trpgindex"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/trpgindex": {
      "filePath": "trpgindex.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
